from enum import Enum


class Event(Enum):
    ENTANGLEMENT_GENERATION = 1
    REQUEST_ARRIVAL = 2


class Strategy(Enum):
    ALWAYS_REPLACE = 1
    ALWAYS_PROT_1 = 2
    ALWAYS_PROT_2 = 3
    ALWAYS_PROT_3 = 4
    ALWAYS_PROT_1_WITH_PROBABILITY = 5
    ALWAYS_PROT_2_WITH_PROBABILITY = 6
    ALWAYS_PROT_3_WITH_PROBABILITY = 7
    CHOOSE_RANDOM_ACTION_UNIFORMLY = 8
    GPS = 9
    ALWAYS_PMD = 10


