

ENTANGLEMENT_GENERATION_SCALE = 0.04
ENTANGLEMENT_GENERATION_COUNT = 1000

ENTANGLEMENT_GENERATION_SUCESS_PROBABILITY = 0.7

ENTANGLEMENT_DECOHERENCE_CONSTANT = 0.01

ENTANGLEMENT_INITIAL_FIDELITY = 0.7