

ENTANGLEMENT_GENERATION_SCALE = 1
ENTANGLEMENT_GENERATION_COUNT = 1000

ENTANGLEMENT_GENERATION_SUCESS_PROBABILITY = 0.7

ENTANGLEMENT_DECOHERENCE_CONSTANT = 10e-9

ENTANGLEMENT_INITIAL_FIDELITY = 0.7