from pygments.token import String
from dataclasses import dataclass

from purify.constants_tuple import ConstantsTuple
from purify.my_enums import Action, LambdaSrategy
from ppo.hyperparams_tuple import HyperparamsTuple


@dataclass
class CaseStudy:
    """
    Definiert eine Case Study: eine festgelegte Umgebungskonfiguration (Constants)
    und eine Liste zu trainierender Kohärenzzeiten.

    Jedes Gerät kann eine Teilmenge der `coherence_times` trainieren.
    Die eigentliche coherence_time wird erst beim Trainingsstart per
    `make_constants()` in das ConstantsTuple eingesetzt.
    """

    id: int
    notes: String
    constants: ConstantsTuple
    hyperparams: HyperparamsTuple
    coherence_times: list[float]
    deterministic: bool = True

    def make_constants(self, coherence_time: float) -> ConstantsTuple:
        """Gibt ein neues ConstantsTuple zurück, bei dem coherence_time gesetzt ist."""
        return self.constants._replace(coherence_time=coherence_time)

    def folder_name(self) -> str:
        return f"case_study_{self.id}"

    @staticmethod
    def coherence_time_str(coherence_time: float) -> str:
        """Erzeugt einen dateisystemfreundlichen Ordnernamen für eine Kohärenzzeit."""
        return f"T{str(coherence_time).replace('.', '_')}"


# ─── Case Studies ─────────────────────────────────────────────────────────────
# Jede Case Study hat eine eindeutige ID (1, 2, 3, …).
# Die coherence_time wird als Platzhalter auf 0.0 gesetzt;
# der tatsächliche Wert wird von make_constants() injiziert.
# ─────────────────────────────────────────────────────────────────────────────

CASE_STUDIES: dict[int, CaseStudy] = {
    1: CaseStudy(
        id=1,
        notes="Standard Entanglement",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.USE_CONSTANTS,
            lambdas=(0.3, 0.0, 0.0),
            actions=(
                Action.REPLACE,
                Action.PROT_1,
                Action.PROT_2,
                Action.PROT_3,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        hyperparams=HyperparamsTuple(
            n_steps=1024,
            batch_size=256,
            n_epochs=6,
            learning_rate=2.9496e-4,
            gamma=1.0,
            gae_lambda=0.99,
            ent_coef=0.003011806764086755,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            # 0.004,
            # 0.005,
            # 0.006,
            # 0.007,
            # 0.008,
            # 0.009,
            # 0.01,
            # 0.02,
            # 0.03,
            # 0.04,
            # 0.05,
            # 0.06,
            0.07,
            0.08,
            0.09,
        ],
    ),
    2: CaseStudy(
        id=2,
        notes="Standard Entanglement",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.USE_CONSTANTS,
            lambdas=(0.0, 0.3, 0.0),
            actions=(
                Action.REPLACE,
                Action.PROT_1,
                Action.PROT_2,
                Action.PROT_3,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        hyperparams=HyperparamsTuple(
            n_steps=1024,
            batch_size=256,
            n_epochs=6,
            learning_rate=2.9496e-4,
            gamma=1.0,
            gae_lambda=0.99,
            ent_coef=0.003011806764086755,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            0.004,
            0.005,
            0.006,
            0.007,
            0.008,
            0.009,
            0.01,
            0.02,
            0.03,
            0.04,
            0.05,
            0.06,
            0.07,
            0.08,
            0.09,
        ],
    ),
    3: CaseStudy(
        id=3,
        notes="Standard Entanglement",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.USE_CONSTANTS,
            lambdas=(0.0, 0.0, 0.3),
            actions=(
                Action.REPLACE,
                Action.PROT_1,
                Action.PROT_2,
                Action.PROT_3,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        hyperparams=HyperparamsTuple(
            n_steps=1024,
            batch_size=256,
            n_epochs=6,
            learning_rate=2.9496e-4,
            gamma=1.0,
            gae_lambda=0.99,
            ent_coef=0.003011806764086755,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            0.004,
            0.005,
            0.006,
            0.007,
            0.008,
            0.009,
            0.01,
            0.02,
            0.03,
            0.04,
            0.05,
            0.06,
            0.07,
            0.08,
            0.09,
            0.1,
        ],
    ),
    4: CaseStudy(
        id=4,
        notes="4-GPS Random",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.RANDOM,
            lambdas=(0.0, 0.0, 0.0),
            actions=(
                Action.REPLACE,
                Action.PROT_1,
                Action.PROT_2,
                Action.PROT_3,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        hyperparams=HyperparamsTuple(
            n_steps=1024,
            batch_size=256,
            n_epochs=6,
            learning_rate=2.9496e-4,
            gamma=1.0,
            gae_lambda=0.99,
            ent_coef=0.003011806764086755,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            0.001,
            0.002,
            0.003,
            # 0.004,
            # 0.005,
            # 0.006,
            # 0.007,
            # 0.008,
            # 0.009,
            # 0.01,
            # 0.02,
            # 0.03,
            # 0.04,
            # 0.05,
            # 0.06,
            # 0.07,
            # 0.08,
            # 0.09,
            # 0.1,
        ],
    ),
    5: CaseStudy(
        id=5,
        notes="Mit PMD",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.USE_CONSTANTS,
            lambdas=(0.3, 0.0, 0.0),
            actions=(
                Action.REPLACE,
                Action.PROT_1,
                Action.PROT_2,
                Action.PROT_3,
                Action.PMD,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        hyperparams=HyperparamsTuple(
            n_steps=256,
            batch_size=128,
            n_epochs=5,
            learning_rate=4.310293e-04,
            gamma=1.0,
            gae_lambda=0.939620,
            ent_coef=8.393195e-04,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            # 0.004,
            # 0.005,
            # 0.006,
            # 0.007,
            # 0.008,
            # 0.009,
            # 0.01,
            # 0.02,
            # 0.03,
            # 0.04,
            # 0.05,
            # 0.06,
            # 0.07,
            0.08,
            # 0.09,
        ],
    ),
    6: CaseStudy(
        id=6,
        notes="lambdas 0.2, 0.1, 0.0",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.USE_CONSTANTS,
            lambdas=(0.2, 0.1, 0.0),
            actions=(
                Action.REPLACE,
                Action.PROT_1,
                Action.PROT_2,
                Action.PROT_3,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        hyperparams=HyperparamsTuple(
            n_steps=1024,
            batch_size=256,
            n_epochs=6,
            learning_rate=2.9496e-4,
            gamma=1.0,
            gae_lambda=0.99,
            ent_coef=0.003011806764086755,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            0.004,
            0.005,
            0.006,
            0.007,
            0.008,
            0.009,
            0.01,
            0.02,
            0.03,
            0.04,
            0.05,
            0.06,
            0.07,
            0.08,
            0.09,
            0.1,
        ],
    ),
    7: CaseStudy(
        id=7,
        notes="Neue Hyperparameter ausprobieren",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.USE_CONSTANTS,
            lambdas=(0.3, 0.0, 0.0),
            actions=(
                Action.REPLACE,
                Action.PROT_1,
                Action.PROT_2,
                Action.PROT_3,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        hyperparams=HyperparamsTuple(
            n_steps=512,
            batch_size=256,
            n_epochs=6,
            learning_rate=3.283142e-04,
            gamma=1.0,
            gae_lambda=0.953157,
            ent_coef=1.713062e-02,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            0.08,
        ],
    ),
    8: CaseStudy(
        id=8,
        notes="Standard entangelemnts, aber training für kleine coherence time mit parametern von 0.008 optuna",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.USE_CONSTANTS,
            lambdas=(0.3, 0.0, 0.0),
            actions=(
                Action.REPLACE,
                Action.PROT_1,
                Action.PROT_2,
                Action.PROT_3,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        hyperparams=HyperparamsTuple(
            n_steps=2048,
            batch_size=256,
            n_epochs=9,
            learning_rate=3.55006612192314e-05,
            gamma=1.0,
            gae_lambda=0.99,
            ent_coef=0.4962618370958482,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[128, 128],
            vf_layers=[128, 128],
        ),
        coherence_times=[
            0.008,
            0.01,
        ],
    ),
    9: CaseStudy(
        id=9,
        notes="Standard Entanglement",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.USE_CONSTANTS,
            lambdas=(0.3, 0.0, 0.0),
            actions=(
                Action.REPLACE,
                Action.PROT_1,
                Action.PROT_2,
                Action.PROT_3,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        hyperparams=HyperparamsTuple(
            n_steps=1024,
            batch_size=256,
            n_epochs=6,
            learning_rate=2.9496e-4,
            gamma=1.0,
            gae_lambda=0.99,
            ent_coef=0.003011806764086755,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            0.004,
            0.005,
            0.006,
            0.007,
            0.008,
            0.009,
            0.01,
            0.02,
            0.03,
            0.04,
            0.05,
            0.06,
            0.07,
            0.08,
            0.09,
        ],
    ),
    10: CaseStudy(
        id=10,
        notes="4-GPS Random",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.RANDOM,
            lambdas=(0.0, 0.0, 0.0),
            actions=(
                Action.REPLACE,
                Action.PROT_1,
                Action.PROT_2,
                Action.PROT_3,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        hyperparams=HyperparamsTuple(
            n_steps=1024,
            batch_size=256,
            n_epochs=6,
            learning_rate=2.9496e-4,
            gamma=1.0,
            gae_lambda=0.99,
            ent_coef=0.003011806764086755,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            0.001,
            0.002,
            0.003,
            0.004,
            0.005,
            0.006,
            0.007,
            0.008,
            0.009,
            0.01,
            # 0.02,
            # 0.03,
            # 0.04,
            # 0.05,
            # 0.06,
            # 0.07,
            # 0.08,
            # 0.09,
            # 0.1,
        ],
    ),
    11: CaseStudy(
        id=11,
        notes="Standard Entanglement",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.USE_CONSTANTS,
            lambdas=(0.0, 0.3, 0.0),
            actions=(
                Action.REPLACE,
                Action.PROT_1,
                Action.PROT_2,
                Action.PROT_3,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        hyperparams=HyperparamsTuple(
            n_steps=1024,
            batch_size=256,
            n_epochs=6,
            learning_rate=2.9496e-4,
            gamma=1.0,
            gae_lambda=0.99,
            ent_coef=0.003011806764086755,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            0.001,
            0.002,
            0.003,
            0.004,
            0.005,
            0.006,
            0.007,
            0.008,
            0.009,
            0.01,
            # 0.02,
            # 0.03,
            # 0.04,
            # 0.05,
            # 0.06,
            # 0.07,
            # 0.08,
            # 0.09,
        ],
    ),
    12: CaseStudy(
        id=12,
        notes="Standard Entanglement",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.USE_CONSTANTS,
            lambdas=(0.0, 0.0, 0.3),
            actions=(
                Action.REPLACE,
                Action.PROT_1,
                Action.PROT_2,
                Action.PROT_3,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        hyperparams=HyperparamsTuple(
            n_steps=1024,
            batch_size=256,
            n_epochs=6,
            learning_rate=2.9496e-4,
            gamma=1.0,
            gae_lambda=0.99,
            ent_coef=0.003011806764086755,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            0.001,
            0.002,
            0.003,
            0.004,
            0.005,
            0.006,
            0.007,
            0.008,
            0.009,
            0.01,
            # 0.02,
            # 0.03,
            # 0.04,
            # 0.05,
            # 0.06,
            # 0.07,
            # 0.08,
            # 0.09,
        ],
    ),
    13: CaseStudy(
        id=13,
        notes="2-GPS PMD, nicht deterministisch",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.USE_CONSTANTS,
            lambdas=(0.3, 0.0, 0.0),
            actions=(Action.REPLACE, Action.PMD),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        deterministic=False,
        hyperparams=HyperparamsTuple(
            n_steps=256,
            batch_size=1024,
            n_epochs=13,
            learning_rate=3.041823e-04,
            gamma=1.0,
            gae_lambda=0.940096,
            ent_coef=1.303879e-07,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            # 0.001,
            # 0.002,
            # 0.003,
            # 0.004,
            # 0.005,
            # 0.006,
            0.007,
            # 0.008,
            # 0.009,
            # 0.01,
            # 0.02,
            # 0.03,
            # 0.04,
            # 0.05,
            # 0.06,
            # 0.07,
            # 0.08,
            # 0.09,
            # 0.1,
        ],
    ),
    14: CaseStudy(
        id=14,
        notes="Mit PMD",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.USE_CONSTANTS,
            lambdas=(0.3, 0.0, 0.0),
            actions=(
                Action.REPLACE,
                Action.PROT_1,
                Action.PROT_2,
                Action.PROT_3,
                Action.PMD,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        hyperparams=HyperparamsTuple(
            n_steps=512,
            batch_size=128,
            n_epochs=15,
            learning_rate=4.721431e-04,
            gamma=1.0,
            gae_lambda=0.938491,
            ent_coef=1.375055e-07,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            # 0.004,
            0.005,
            # 0.006,
            # 0.007,
            # 0.008,
            # 0.009,
            # 0.01,
            # 0.02,
            # 0.03,
            # 0.04,
            # 0.05,
            # 0.06,
            # 0.07,
            # 0.08,
            # 0.09,
        ],
    ),
    15: CaseStudy(
        id=15,
        notes="5-GPS nicht-deterministisch, params von optuna für t_c 0.01",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.USE_CONSTANTS,
            lambdas=(0.3, 0.0, 0.0),
            actions=(
                Action.REPLACE,
                Action.PROT_1,
                Action.PROT_2,
                Action.PROT_3,
                Action.PMD,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        deterministic=False,
        hyperparams=HyperparamsTuple(
            n_steps=512,
            batch_size=128,
            n_epochs=15,
            learning_rate=4.622589e-04,
            gamma=1.0,
            gae_lambda=0.921234,
            ent_coef=1.874022e-07,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            # 0.004,
            # 0.005,
            # 0.006,
            0.007,
            # 0.008,
            # 0.009,
            0.01,
            # 0.02,
            # 0.03,
            0.04,
            # 0.05,
            # 0.06,
            0.07,
            # 0.08,
            # 0.09,
            0.1,
        ],
    ),
    17: CaseStudy(
        id=17,
        notes="Standard Entanglement",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.USE_CONSTANTS,
            lambdas=(0.3, 0.0, 0.0),
            actions=(
                Action.REPLACE,
                Action.PROT_1,
                Action.PROT_2,
                Action.PROT_3,
                Action.PMD,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        hyperparams=HyperparamsTuple(
            n_steps=1024,
            batch_size=256,
            n_epochs=6,
            learning_rate=2.9496e-4,
            gamma=1.0,
            gae_lambda=0.99,
            ent_coef=0.003011806764086755,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            # 0.001,
            # 0.002,
            # 0.003,
            # 0.004,
            # 0.005,
            # 0.006,
            0.007,
            # 0.008,
            # 0.009,
            0.01,
            # 0.02,
            # 0.03,
            # 0.04,
            0.05,
            # 0.06,
            # 0.07,
            0.08,
            # 0.09,
            # 0.1
        ],
    ),
    18: CaseStudy(
        id=18,
        notes="Standard Entanglement",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.USE_CONSTANTS,
            lambdas=(0.3, 0.0, 0.0),
            actions=(
                Action.REPLACE,
                Action.PMD,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        hyperparams=HyperparamsTuple(
            n_steps=1024,
            batch_size=256,
            n_epochs=6,
            learning_rate=2.9496e-4,
            gamma=1.0,
            gae_lambda=0.99,
            ent_coef=0.003011806764086755,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            0.001,
            0.002,
            # 0.003, trained
            0.004,
            # 0.005, trained
            0.006,
            # 0.007, trained
            # 0.008, trained
            0.009,
            # 0.01, trained
            0.02,
            # 0.03, , trained
            0.04,
            # 0.05, trained
            0.06,
            # 0.07, trained
            # 0.08, trained
            0.09,
            # 0.1 , trained
        ],
    ),
    19: CaseStudy(
        id=19,
        notes="2-GPS ohne PMD",
        constants=ConstantsTuple(
            coherence_time=0.0,  # Platzhalter – wird per make_constants() überschrieben
            pumping_probability=1,
            waiting_time_sensitivity=1,
            lambda_strategy=LambdaSrategy.USE_CONSTANTS,
            lambdas=(0.3, 0.0, 0.0),
            actions=(
                Action.REPLACE,
                Action.PROT_2,
            ),
            min_fidelity=0.7,
            max_fidelity=0.7,
        ),
        deterministic=False,
        hyperparams=HyperparamsTuple(
            n_steps=1024,
            batch_size=256,
            n_epochs=6,
            learning_rate=2.9496e-4,
            gamma=1.0,
            gae_lambda=0.99,
            ent_coef=0.003011806764086755,
            clip_range=0.2,
            vf_coef=0.5,
            max_grad_norm=0.5,
            pi_layers=[256, 256],
            vf_layers=[256, 256],
        ),
        coherence_times=[
            # 0.001,
            0.002,
            # 0.003, trained
            0.004,
            # 0.005, trained
            0.006,
            # 0.007, trained
            # 0.008, trained
            0.009,
            # 0.01, trained
            0.02,
            # 0.03, , trained
            0.04,
            # 0.05, trained
            0.06,
            # 0.07, trained
            # 0.08, trained
            0.09,
            # 0.1 , trained
        ],
    ),
}
